version: '3.8'
services:
  db:
    image: mongo:6
    container_name: urbaneye-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
